site_name: Wiki 安裝工程
site_url: https://drogan-gas.github.io/KK/

theme:
  name: material
  palette:
    scheme: slate
    primary: custom
    accent: custom
  features:
    - content.code.copy
    - toc.follow
    - navigation.top
  font: false

plugins:
  - search
  - roamlinks

docs_dir: 'WebWiki'

extra_css:
  - "https://fonts.googleapis.com/css2?family=Iansui&display=swap"
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
      baselevel: 1
      toc_depth: '1-6'

extra_javascript:
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js